// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9Vkntdzo4gwe-sLt4za71gYfvycKdJw',
    appId: '1:559475050011:web:e22d5691d4dea160fcdabe',
    messagingSenderId: '559475050011',
    projectId: 'ieee-website-ebd9a',
    authDomain: 'ieee-website-ebd9a.firebaseapp.com',
    storageBucket: 'ieee-website-ebd9a.firebasestorage.app',
    measurementId: 'G-BCB24FEEQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1leuibJJAgSHnk-nfqluOA5zp3bSsQwQ',
    appId: '1:559475050011:android:6f300d9b0201128dfcdabe',
    messagingSenderId: '559475050011',
    projectId: 'ieee-website-ebd9a',
    storageBucket: 'ieee-website-ebd9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSil5neJt7ZS9dOXg1vF_zIepS7i8Ann4',
    appId: '1:559475050011:ios:5c505e4cbd4cb4ccfcdabe',
    messagingSenderId: '559475050011',
    projectId: 'ieee-website-ebd9a',
    storageBucket: 'ieee-website-ebd9a.firebasestorage.app',
    iosBundleId: 'com.example.ieeeWebsiteAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSil5neJt7ZS9dOXg1vF_zIepS7i8Ann4',
    appId: '1:559475050011:ios:5c505e4cbd4cb4ccfcdabe',
    messagingSenderId: '559475050011',
    projectId: 'ieee-website-ebd9a',
    storageBucket: 'ieee-website-ebd9a.firebasestorage.app',
    iosBundleId: 'com.example.ieeeWebsiteAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD9Vkntdzo4gwe-sLt4za71gYfvycKdJw',
    appId: '1:559475050011:web:1d4510a4e809efb8fcdabe',
    messagingSenderId: '559475050011',
    projectId: 'ieee-website-ebd9a',
    authDomain: 'ieee-website-ebd9a.firebaseapp.com',
    storageBucket: 'ieee-website-ebd9a.firebasestorage.app',
    measurementId: 'G-NJVH67BWJJ',
  );
}
